### ISSUE TITLE
Feedback on particle module

### ISSUE THREAD

**Issue by eduardo-rodrigues** [henryiii/decaylanguage#5]
Non-python files in decaylanguage/particle/
-------------------------------------------------

I reckon it would be better to move those .txt and .csv files out of the python submodule,
similarly to what we did in https://github.com/scikit-hep/scikit-hep/tree/master/skhep/data.
At some point one might even consider a data package in Scikit-HEP, BTW ... But this move is just fine for now, I think.

I would also rename mass_width.csv to explicitly include the year, as that's relevant for a user to know that the file provided by the PDG is a decade old. So rename to mass_width_2008.csv.
This way, if we get the courage to update the file ourselves, we can give a hint in the filename.

pdgID_to_latex.txt
--------------------
It would make sense to add a header with basic information, even if trivial. So, headers for the 3 columns at least, maybe also the date at which the file was created/checked.

particle.py
-----------
AmpGen is there even in methods and it it important to give some reference for it.
Also the docstring with "from an AmpGen style name" could be extended to hint at what the style is.

**Comment by henryiii** [comment]
A few extra points:

* Link to AmpGen
* Expand docs just a bit

**Comment by eduardo-rodrigues** [comment]
Dealt with in https://github.com/henryiii/decaylanguage/pull/8.
